# example:
# https://gitlab.com/allamand/example-voting-app/-/blob/master/.gitlab-ci.yml

image: docker:stable

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:dind

stages:
  - build

before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_python_app:
  stage: build
  script:
    - docker build --tag $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID --tag $CI_REGISTRY_IMAGE:latest .
    # add tag "latest"
    - docker tag $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID
    - docker push $CI_REGISTRY_IMAGE:latest
