version: '3.8'

services:
  app:
    image: azure-node-app:latest
    build: .
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - database

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - database

networks:
  database:
    driver: bridge
